version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - kelinci-mq
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - kelinci-mq

networks:
  kelinci-mq:
    driver: bridge
